// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AuroraDbContext))]
    [Migration("20250202220309_Basic_Db_Without_Relations")]
    partial class Basic_Db_Without_Relations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Advert", b =>
                {
                    b.Property<int>("AdvertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertID"));

                    b.Property<string>("AdvertDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ApplicationAmount")
                        .HasColumnType("int");

                    b.Property<bool>("CVMandatory")
                        .HasColumnType("bit");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<int>("ContractTypeID")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentTypeID")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("JobSectorID")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxSalary")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("MinSalary")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<int>("SeniorityLevelID")
                        .HasColumnType("int");

                    b.Property<int>("WorkDaysID")
                        .HasColumnType("int");

                    b.Property<int>("WorkModelID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("WorkTimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("WorkTimeTo")
                        .HasColumnType("time");

                    b.HasKey("AdvertID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("ContractTypeID");

                    b.HasIndex("EmploymentTypeID");

                    b.HasIndex("JobSectorID");

                    b.HasIndex("PositionID");

                    b.HasIndex("SeniorityLevelID");

                    b.HasIndex("WorkDaysID");

                    b.HasIndex("WorkModelID");

                    b.ToTable("Advert");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.AdvertDuty", b =>
                {
                    b.Property<int>("AdvertDutyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertDutyID"));

                    b.Property<int>("AdvertID")
                        .HasColumnType("int");

                    b.Property<int>("DutyID")
                        .HasColumnType("int");

                    b.HasKey("AdvertDutyID");

                    b.HasIndex("DutyID");

                    b.ToTable("AdvertDuty");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.Benefit", b =>
                {
                    b.Property<int>("BenefitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefitID"));

                    b.Property<int>("AdvertID")
                        .HasColumnType("int");

                    b.Property<string>("BenefitDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BenefitID");

                    b.HasIndex("AdvertID");

                    b.ToTable("Benefit");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.ContractType", b =>
                {
                    b.Property<int>("ContractTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractTypeID"));

                    b.Property<string>("ContractTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContractTypeID");

                    b.ToTable("ContractType");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.EmploymentType", b =>
                {
                    b.Property<int>("EmploymentTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmploymentTypeID"));

                    b.Property<string>("EmploymentTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EmploymentTypeID");

                    b.ToTable("EmploymentType");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.JobSector", b =>
                {
                    b.Property<int>("JobSectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobSectorID"));

                    b.Property<string>("JobSectorName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JobSectorID");

                    b.ToTable("JobSector");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.Requirment", b =>
                {
                    b.Property<int>("RequirmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirmentID"));

                    b.Property<int>("AdvertID")
                        .HasColumnType("int");

                    b.Property<string>("RequirmentDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RequirmentID");

                    b.HasIndex("AdvertID");

                    b.ToTable("Requirment");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.SeniorityLevel", b =>
                {
                    b.Property<int>("SeniorityLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeniorityLevelID"));

                    b.Property<string>("SeniorityLevelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SeniorityLevelID");

                    b.ToTable("SeniorityLevel");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.WorkDays", b =>
                {
                    b.Property<int>("WorkDaysID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkDaysID"));

                    b.Property<string>("WorkDaysName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkDaysID");

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.WorkModel", b =>
                {
                    b.Property<int>("WorkModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkModelID"));

                    b.Property<string>("WorkModelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkModelID");

                    b.ToTable("WorkModel");
                });

            modelBuilder.Entity("Core.Entities.Shared.Company.Company", b =>
                {
                    b.Property<int>("CompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyID"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("Core.Entities.Shared.Company.CompanyAdress", b =>
                {
                    b.Property<int>("CompanyAdressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyAdressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CompanyAdressID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyAdress");
                });

            modelBuilder.Entity("Core.Entities.Shared.Duty", b =>
                {
                    b.Property<int>("DutyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DutyID"));

                    b.Property<string>("DutyName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("DutyID");

                    b.ToTable("Duty");
                });

            modelBuilder.Entity("Core.Entities.Shared.Position", b =>
                {
                    b.Property<int>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionID"));

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PositionID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("CVPath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<string>("ProfilePicturePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WorkSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("PositionID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CourseID");

                    b.HasIndex("UserID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Education.Education", b =>
                {
                    b.Property<int>("EducationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("EduacationLevelID")
                        .HasColumnType("int");

                    b.Property<int>("EducationLevelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("EducationID");

                    b.HasIndex("EducationLevelID");

                    b.HasIndex("UserID");

                    b.ToTable("Education");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Education.EducationLevel", b =>
                {
                    b.Property<int>("EducationLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationLevelID"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EducationLevelID");

                    b.ToTable("EducationLevel");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Experience.Experience", b =>
                {
                    b.Property<int>("ExperienceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ExperienceID");

                    b.HasIndex("CompanyID");

                    b.HasIndex("PositionID");

                    b.HasIndex("UserID");

                    b.ToTable("Experience");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Experience.ExperienceDuty", b =>
                {
                    b.Property<int>("ExperienceDutyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceDutyID"));

                    b.Property<int>("DutyID")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceID")
                        .HasColumnType("int");

                    b.HasKey("ExperienceDutyID");

                    b.HasIndex("DutyID");

                    b.HasIndex("ExperienceID");

                    b.ToTable("ExperienceDuty");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Language.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("LanguageID");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Language.LanguageLevel", b =>
                {
                    b.Property<int>("LanguageLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageLevelID"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("LanguageLevelID");

                    b.ToTable("LanguageLevel");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Language.UserLanguage", b =>
                {
                    b.Property<int>("UserLanguageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLanguageID"));

                    b.Property<int>("LanguageID")
                        .HasColumnType("int");

                    b.Property<int>("LanguageLevelID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserLanguageID");

                    b.HasIndex("LanguageID");

                    b.HasIndex("LanguageLevelID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLanguage");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Link", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkID"));

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("LinkID");

                    b.HasIndex("UserID");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Skill.Skill", b =>
                {
                    b.Property<int>("SkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SkillID");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Skill.UserSkill", b =>
                {
                    b.Property<int>("UserSkillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserSkillID"));

                    b.Property<int>("SkillID")
                        .HasColumnType("int");

                    b.Property<int>("SkillLevel")
                        .HasMaxLength(15)
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserSkillID");

                    b.HasIndex("SkillID");

                    b.HasIndex("UserID");

                    b.ToTable("UserSkill");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.UserAdress", b =>
                {
                    b.Property<int>("UserAdressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAdressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserAdressID");

                    b.HasIndex("UserID");

                    b.ToTable("UserAdress");
                });

            modelBuilder.Entity("Core.Entities.Advert", b =>
                {
                    b.HasOne("Core.Entities.Shared.Company.Company", null)
                        .WithMany("Adverts")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AdvertDependent.ContractType", null)
                        .WithMany("Adverts")
                        .HasForeignKey("ContractTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AdvertDependent.EmploymentType", null)
                        .WithMany("Adverts")
                        .HasForeignKey("EmploymentTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AdvertDependent.JobSector", null)
                        .WithMany("Adverts")
                        .HasForeignKey("JobSectorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Shared.Position", null)
                        .WithMany("Adverts")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AdvertDependent.SeniorityLevel", null)
                        .WithMany("Adverts")
                        .HasForeignKey("SeniorityLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AdvertDependent.WorkDays", null)
                        .WithMany("Adverts")
                        .HasForeignKey("WorkDaysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.AdvertDependent.WorkModel", null)
                        .WithMany("Adverts")
                        .HasForeignKey("WorkModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.AdvertDuty", b =>
                {
                    b.HasOne("Core.Entities.Shared.Duty", "Duty")
                        .WithMany("AdvertDuties")
                        .HasForeignKey("DutyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duty");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.Benefit", b =>
                {
                    b.HasOne("Core.Entities.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.Requirment", b =>
                {
                    b.HasOne("Core.Entities.Advert", "Advert")
                        .WithMany()
                        .HasForeignKey("AdvertID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Core.Entities.Shared.Company.CompanyAdress", b =>
                {
                    b.HasOne("Core.Entities.Shared.Company.Company", "Company")
                        .WithMany("CompanyAdresses")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.HasOne("Core.Entities.Shared.Company.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Shared.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Course", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Courses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Education.Education", b =>
                {
                    b.HasOne("Core.Entities.UserDependent.Education.EducationLevel", "EducationLevel")
                        .WithMany("Educations")
                        .HasForeignKey("EducationLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Educations")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Experience.Experience", b =>
                {
                    b.HasOne("Core.Entities.Shared.Company.Company", "Company")
                        .WithMany("Experiences")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Shared.Position", "Position")
                        .WithMany("Experiences")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Experience.ExperienceDuty", b =>
                {
                    b.HasOne("Core.Entities.Shared.Duty", "Duty")
                        .WithMany("ExperienceDuties")
                        .HasForeignKey("DutyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserDependent.Experience.Experience", "Experience")
                        .WithMany("ExperienceDuties")
                        .HasForeignKey("ExperienceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Duty");

                    b.Navigation("Experience");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Language.UserLanguage", b =>
                {
                    b.HasOne("Core.Entities.UserDependent.Language.Language", "Language")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.UserDependent.Language.LanguageLevel", "LanguageLevel")
                        .WithMany("UserLanguages")
                        .HasForeignKey("LanguageLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserLanguages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LanguageLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Link", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("Links")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Skill.UserSkill", b =>
                {
                    b.HasOne("Core.Entities.UserDependent.Skill.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.UserAdress", b =>
                {
                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserAdresses")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.ContractType", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.EmploymentType", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.JobSector", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.SeniorityLevel", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.WorkDays", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Core.Entities.AdvertDependent.WorkModel", b =>
                {
                    b.Navigation("Adverts");
                });

            modelBuilder.Entity("Core.Entities.Shared.Company.Company", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("CompanyAdresses");

                    b.Navigation("Experiences");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Entities.Shared.Duty", b =>
                {
                    b.Navigation("AdvertDuties");

                    b.Navigation("ExperienceDuties");
                });

            modelBuilder.Entity("Core.Entities.Shared.Position", b =>
                {
                    b.Navigation("Adverts");

                    b.Navigation("Experiences");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Links");

                    b.Navigation("UserAdresses");

                    b.Navigation("UserLanguages");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Education.EducationLevel", b =>
                {
                    b.Navigation("Educations");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Experience.Experience", b =>
                {
                    b.Navigation("ExperienceDuties");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Language.Language", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Language.LanguageLevel", b =>
                {
                    b.Navigation("UserLanguages");
                });

            modelBuilder.Entity("Core.Entities.UserDependent.Skill.Skill", b =>
                {
                    b.Navigation("UserSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
